# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LogScreen(object):
    def setupUi(self, LogScreen):
        LogScreen.setObjectName("LogScreen")
        LogScreen.resize(1920, 1080)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        LogScreen.setFont(font)
        LogScreen.setStyleSheet("QWidget {background : rgba(255, 255, 255); }")
        self.centralwidget = QtWidgets.QWidget(LogScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 465, 1920, 150))
        self.label.setMaximumSize(QtCore.QSize(1920, 500))
        font = QtGui.QFont()
        font.setFamily("华文新魏")
        font.setPointSize(110)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {color : rgb(0, 191, 255); }")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setIndent(5)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 150, 1920, 100))
        self.label_2.setMinimumSize(QtCore.QSize(1920, 0))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(70)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("QLabel {color : rgb(0, 191, 255); }")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        LogScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogScreen)
        QtCore.QMetaObject.connectSlotsByName(LogScreen)

    def retranslateUi(self, LogScreen):
        _translate = QtCore.QCoreApplication.translate
        LogScreen.setWindowTitle(_translate("LogScreen", "MainWindow"))
        self.label.setText(_translate("LogScreen", "中科睿信"))
        self.label_2.setText(_translate("LogScreen", "Radsim"))
